kind: Deployment
apiVersion: apps/v1
metadata:
  name: journeyjinni-backend
  namespace: journeyjinni
spec:
  selector:
    matchLabels:
      app: journeyjinni-backend
  template:
    metadata:
      labels:
        app: journeyjinni-backend
    spec:
      containers: []
