apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: journeyjinni-backend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /default
        pathType: Prefix
        backend:
          service:
            name: placeholder-service
            port:
              number: 80
