apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journeyjinni


resources:
- service.yaml
- deployment.yaml
- secret.yaml
- configmap.yaml

images:
- name: jinnicontainerregistry.azurecr.io/jinni
  newTag: "20241113005102"
