apiVersion: apps/v1
kind: Deployment
metadata:
  name: journeyjinni-frontend
  namespace: journeyjinni
spec:
  template:
    spec:
      containers:
      - name: journeyjinni-frontend
        image: jinniregistry.azurecr.io/jinni
        ports:
        - containerPort: 5173
