apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: journeyjinni

images:
- name: jinniregistry.azurecr.io/jinni
  newTag: front_20250129075704

resources:
- ../../base

patches:
- path: deployment-patches.yaml
- path: service-patches.yaml
