apiVersion: apps/v1
kind: Deployment
metadata:
  name: journeyjinni-backend
spec:
  template:
    spec:
      containers:
      - name: journeyjinni-backend
        image: your-container-image:latest
        ports:
        - containerPort: 8080
