apiVersion: apps/v1
kind: Deployment
metadata:
  name: journeyjinni-backend
spec:
  template:
    spec:
      containers:
      - name: journeyjinni-backend
        image: jinnicontainerregistry.azurecr.io/jinni:{{newTag}}
        ports:
        - containerPort: 8080
