apiVersion: apps/v1
kind: Deployment
metadata:
  name: journeyjinni-backend
spec:
  replicas: 1  # 개발 환경에서는 하나의 인스턴스만 사용
  template:
    spec:
      containers:
        - name: journeyjinni-backend
          image: jinnicontainerregistry.azurecr.io/jinni
          ports:
            - containerPort: 8080
