apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: journeyjinni

bases:
  - ../../base

  # Dev 환경에서 사용할 추가적인 패치를 적용
patchesStrategicMerge:
  - deployment-patches.yaml
  - service-patches.yaml
