apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: journeyjinni

images:
- name: jinnicontainerregistry.azurecr.io/jinni
  newTag: "20241113094323"

resources:
  - ../../base

patches:
  - path: deployment-patches.yaml
  - path: service-patches.yaml
