apiVersion: v1  # API 버전
kind: Service  # 리소스 유형
metadata:  # 서비스 이름, 네임스페이스, 리소스 식별을 위한 라벨 설정
  name: journeyjinni-backend
  namespace: journeyjinni
  labels:
    app: journeyjinni-backend
    chart: journeyjinni-backend-1.0.0
    release: journeyjinni-backend-dev
spec:  # 서비스의 특성과 동작을 정의
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:  # pod를 선택
    app: journeyjinni-backend
  type: LoadBalancer
  sessionAffinity: None
