apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journeyjinni-web



resources:
- secret.yaml
- configmap.yaml
- deployment.yaml
- service.yaml

images:
- name: jinnicontainerregistry.azurecr.io/jinni
  newTag: "20241113094323"
